(define-package "org-iv" "20160609.1854" "a tool used to view html (in browser) generated by org-file once the org-file changes"
  '((impatient-mode "1.0.0")
    (org "8.0")
    (cl-lib "0.5")))
;; Local Variables:
;; no-byte-compile: t
;; End:
