;;; org-iv-autoloads.el --- automatically extracted autoloads
;;
;;; Code:
(add-to-list 'load-path (directory-file-name (or (file-name-directory #$) (car load-path))))

;;;### (autoloads nil "org-iv" "org-iv.el" (22592 24903 483782 420000))
;;; Generated autoloads from org-iv.el

(autoload 'org-iv/immediate-view "org-iv" "\
Use impatient-mode to view html-file generated by org-file quickly.

\(fn CONFIG-NAME)" t nil)

;;;***

;;;### (autoloads nil nil ("org-iv-config.el" "org-iv-pkg.el") (22592
;;;;;;  24903 573781 451000))

;;;***

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; End:
;;; org-iv-autoloads.el ends here
